esphome:
  name: floor-heating
  friendly_name: Floor Heating

external_components:
  - source:
      type: local
      path: custom

esp32:
  board: esp32dev
  framework:
    type: arduino    

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

# Enable Home Assistant API
api:
  encryption:
    key: "dYV2JhTMkSGQP6w0hvIgZHiA3pKz+IUd0TXT55WJ+Jw="

ota:
  - platform: esphome
    password: "63aea147fde87c978ac0823e9e3c28ce"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Floor-Heating Fallback Hotspot"
    password: "PrhK5QtiiUA5"

captive_portal:
       
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 19200
  debug:
    direction: TX
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

#time:
#  - platform: homeassistant
#    id: homeassistant_time

uponor_smatrix145:         
#  known addresses:
#  0x1204 0x2CCC - I-143 Schaltuhr
#  0x1104 0x497D - I-149 Thermonstat digital -> Wohnzimmer
#  0x110E 0xB075 - I-149 Thermonstat digital -> Schlafzimmer
#  0x110E 0xB09E - I-149 Thermonstat digital -> Bad
#  0x1004 0x45F1 - I-144 Thermonstat analog -> Küche
#  0x1004 0x45E8 - I-144 Thermonstat analog -> Computerzimmer
#  0x1004 0x45EF - I-144 Thermonstat analog -> Flur
#system address (only for correct run source code)
  address: 0x1204 
# set time to I-143 not working now
#  time_id: homeassistant_time
#  time_device_address: 0x2CCC

text_sensor:
  - platform: uponor_smatrix145
    system_address: 0x1204
    address: 0x2CCC
    type: I-143 
    timer_datetime:
      name: Timer Datetime
    timer_heating_mode:
      name: Timer Heating Mode
    timer_vacation_mode:
      name: Timer Vacation Mode
    timer_calibration_mode:
      name: Timer calibration Mode

#  - platform: template
#    name: Timer Heating Mode
#    lambda: !lambda |-
#      if (id(id_eco_mode).state == 1) {
#        return {"OFF"};
#      } else {
#        return {"ON"};
#      }

#  - platform: template
#    name: Timer Clock
#    update_interval: 30s
#    lambda: !lambda |-
#      { 
#        return { str_sprintf("%02.0f.%02.0f.%4.0f %02.0f:%02.0f", id(id_day).state, id(id_month).state, id(id_year).state, id(id_hour).state, id(id_minute).state ) };
#      }

#  - platform: template
#    name: Timer Clock 2
#    update_interval: 30s
#    lambda: !lambda |-
#      { 
#        return { str_sprintf("%02d.%02d.%4d %02d:%02d", ((int)(id(id_timepart2).state) >> 11 & 0x001F), 
#                  ((int)(id(id_timepart1).state) >> 3 & 0x000F), (((int)(id(id_timepart1).state) >> 7 & 0x007F) + 0x07D0), 
#                  ((int)(id(id_timepart2).state) >> 6 & 0x001F), ((int)(id(id_timepart2).state) & 0x003F) ) };
#      }

sensor:
  - platform: uponor_smatrix145  
    system_address: 0x1204
    address: 0x2CCC
    type: I-143 
    timer_eco_setback:
      name: Timer ECO Setback
    timer_eco_mode:
      name: Timer ECO Mode
      id: id_eco_mode
      # on_value:
      #   then:          
      #     - climate.control:              
      #         id: Thermostat_Wohnzimmer
      #         preset: !lambda if (x == 1) { return CLIMATE_PRESET_ECO; } else { return CLIMATE_PRESET_NONE; }
      #     - climate.control:              
      #         id: Thermostat_Schlafzimmer
      #         preset: !lambda if (x == 1) { return CLIMATE_PRESET_ECO; } else { return CLIMATE_PRESET_NONE; }
      #     - climate.control:              
      #         id: Thermostat_Bad
      #         preset: !lambda if (x == 1) { return CLIMATE_PRESET_ECO; } else { return CLIMATE_PRESET_NONE; }

  - platform: uponor_smatrix145    
    system_address: 0x1108
    address: 0x497D
    type: T-149    
    humidity:
      name: Humidity Wohnzimmer
    temperature:
      name: Temperature Wohnzimmer        
    target_temperature:
      name: Target Temperature Wohnzimmer
    target_temperature_brutto:
      name: Target Temperature Wohnzimmer Brutto
    eco_setback:
      name: Eco Setback Wohnzimmer
    climate_preset_mode:
      name: Climate Preset Wohnzimmer

  - platform: uponor_smatrix145
    system_address: 0x110E
    address: 0xB075
    type: T-149
    humidity:
      name: Humidity Schlafzimmer
    temperature:
      name: Temperature Schlafzimmer
    target_temperature:
      name: Target Temperature Schlafzimmer
    target_temperature_brutto:
      name: Target Temperature Schlafzimmer Brutto
    eco_setback:
      name: Eco Setback Schlafzimmer
    climate_preset_mode:
      name: Climate Preset Schlafzimmer
  
  - platform: uponor_smatrix145
    system_address: 0x110E
    address: 0xB09E
    type: T-149
    humidity:
      name: Humidity Bad
    temperature:
      name: Temperature Bad
    target_temperature:
      name: Target Temperature Bad
    target_temperature_brutto:
      name: Target Temperature Bad Brutto
    eco_setback:
      name: Eco Setback Bad
    climate_preset_mode:
      name: Climate Preset Bad

  - platform: uponor_smatrix145  
    system_address: 0x1004
    address: 0x45F1
    type: T-144
    temperature:
      name: Temperature Küche
    target_temperature:
      name: Target Temperature Küche

  - platform: uponor_smatrix145
    system_address: 0x1004
    address: 0x45E8
    type: T-144
    temperature:
      name: Temperature Computerzimmer
    target_temperature:
      name: Target Temperature Computerzimmer
   
  - platform: uponor_smatrix145
    system_address: 0x1004
    address: 0x45EF
    type: T-144
    temperature:
      name: Temperature Flur
    target_temperature:
      name: Target Temperature Flur

climate: 
  - platform: uponor_smatrix145  
    system_address: 0x1108
    address: 0x497D
    name: Thermostat Wohnzimmer
    id: Thermostat_Wohnzimmer

  - platform: uponor_smatrix145
    system_address: 0x110E
    address: 0xB075
    name: Thermostat Schlafzimmer
    id: Thermostat_Schlafzimmer
  
  - platform: uponor_smatrix145
    system_address: 0x110E
    address: 0xB09E
    name: Thermostat Bad
    id: Thermostat_Bad

  # - platform: uponor_smatrix145  
  #   system_address: 0x1004
  #   address: 0x45F1
  #   name: Thermostat Küche

  # - platform: uponor_smatrix145  
  #   system_address: 0x1004
  #   address: 0x45E8
  #   name: Thermostat Computerzimmer

  # - platform: uponor_smatrix145  
  #   system_address: 0x1004
  #   address: 0x45EF
  #   name: Thermostat Flur
